### ISSUE TITLE
`.valueOf` is being added to `this`

### ISSUE THREAD

**Issue by STRd6** [phil294/coffeesense#13]
```coffee
@
```

Actual:
```js
this.valueOf()
```

Expected:
```js
this
```

I tested in CoffeeScript 2.6.1 as well as the var-assign branch and those were both correct so I think `valueOf` is being added by the extension.

**Comment by phil294** [comment]
when or where do you see this `.valueOf` and how or where is this a problem? As long as it doesn't affect autocomplete etc. I think it should not matter (?)

**Comment by STRd6** [comment]
![Screenshot 2022-04-27 120302](https://user-images.githubusercontent.com/18894/165600717-42361940-fc70-4fe6-ae4f-54d0db2b01a4.png)

The type of `@` becomes `Object` after `.valueOf()` is attached to it causing a spurious type error.
