### ISSUE TITLE
Issues that I can't seem to figure out

### ISSUE THREAD

**Issue by rayzorben** [phil294/coffeesense#17]
I keep getting weird errors that don't make sense. Take for example this one that says unmatched OUTDENT. I have tried reindenting, deleting the line (which shifts the error to the next one). I have removed the whole block and it just shifts it to the id function

<img width="507" alt="image" src="https://github.com/phil294/coffeesense/assets/7737834/75c801d2-d70a-440f-87e1-01bc9827f454">

Or this one that I am missing a } which is clearly there

<img width="405" alt="image" src="https://github.com/phil294/coffeesense/assets/7737834/d18ce509-3e01-4f28-a71c-25d15b0e2408">

**Comment by rayzorben** [comment]
Here is some code that is causing a problem:

```coffeescript
 
    getColorCodes: (input) ->
        colorPattern = /\x1B\[([0-9;]*)m/

        match = input.match colorPattern
        if match then match[1].split ';' else []
            
    handleCursor: (sequence) ->
```

The if statement which returns a value as an expression 

<img width="523" alt="image" src="https://github.com/phil294/coffeesense/assets/7737834/93b8be00-6569-4e72-9b6b-26deb74eb723">

If I restructure it as 

```coffeescript
 getColorCodes: (input) ->
        colorPattern = /\x1B\[([0-9;]*)m/

        match = input.match colorPattern
        result = if match then match[1].split ';' else []
        result
            
    handleCursor: (sequence) ->
```

it is fine.

**Comment by rayzorben** [comment]
Once I add a switch statement here, it throws this error

<img width="613" alt="image" src="https://github.com/phil294/coffeesense/assets/7737834/7f81b072-6e2f-4ae2-a406-e30026d3c2f1">

<img width="391" alt="image" src="https://github.com/phil294/coffeesense/assets/7737834/ce0677d3-aba3-47f5-be06-49bdd889704d">

**Comment by rayzorben** [comment]
one thing ive found is trailing spaces will cause issues

```
@keys = '' 
```

there is a trailing space there after '' and it will cause other errors in the file.

**Comment by phil294** [comment]
That seems to be indeed all caused by some whitespace. Please read https://github.com/phil294/coffeesense#known-problems, especially the `editor.trimAutoWhitespace` paragraph
