### ISSUE TITLE
Project template?

### ISSUE THREAD

**Issue by isral** [phil294/coffeesense#4]
Do you have template folder for VSCode CoffeeSense project with build task, preferably with file system watcher capability?
```/docs/guide/setup.md``` assume everything already works.
Thanks

**Comment by phil294** [comment]
not really sure what you mean - there should be *no* setup necessary, just install the extension, open up a `.coffee` file and you are good to go. The compilation etc. all happens internally.

To get type checks, you of course also need
> Be sure to include `# @ts-check` at the top of your script or set checkJs=true in your jsconfig.json

But that's just the same thing you would need with a regular JavaScript project. Maybe I am missing something?
