### ISSUE TITLE
Wrong error in CoffeeScript compiler repo

### ISSUE THREAD

**Issue by blaumeise20** [phil294/coffeesense#8]
I just cloned the official compiler repository, and I got this error with this extension:

<img width="899" alt="Bildschirmfoto 2022-02-22 um 18 36 13" src="https://user-images.githubusercontent.com/62756994/155196850-dc1765c9-2ba3-4406-ad4f-4355cb9d68fc.png">

So this means the compiler has a syntax error? Can't be the case. Please fix this!

**Comment by phil294** [comment]
CoffeeSense cannot handle lines that end with an opening brace, such as `flatten(` in the given code snippet.

This is a bug - I'll try to fix it soon

**Comment by phil294** [comment]
hi @blaumeise20, this should now be fixed in published version 1.3.0. Thanks for the report
