### ISSUE TITLE
Please add support for coffee2 files!

### ISSUE THREAD

**Issue by ritute** [phil294/coffeesense#9]

**Comment by phil294** [comment]
Good idea. I think this should simply be configurable. Is `.coffee2` somewhat standardized or is it just you? If the former, then I'll add it to the default extensions

**Comment by phil294** [comment]
More concretely, I think that this must be doable without an extension config option, by setting vscode setting

```js
"files.associations": {
  "*.coffee2": "coffeescript"
```

and CoffeeSense should respect that setting. It does not, currently. However for LSP usage outside of VSCode, there still needs to be an extension option either way.

**Comment by ritute** [comment]
Hmm, it's a convention we're using to be able to support both compilers as we haven't migrated fully. Not sure if it's standardized. We do have that file association set up in VSCode, but that doesn't work - get a bunch of red squigglys in the coffee2 files from CoffeeSense.

**Comment by phil294** [comment]
This is now possible with version 1.3.0 (you need to check that VSCode updated the extension, it usually takes two reloads for that). Check [setup.md](https://github.com/phil294/coffeesense/blob/master/docs/guide/setup.md) - can you test this out and tell me if it now works as desired?

**Comment by ritute** [comment]
Awesome, works now, thank you so much!! 🎉
